import { DeviceSensor, Vehicle, VehicleType } from '../types/simulator';

// Preset sensors and devices by vehicle type
export const PRESET_SENSORS: Record<VehicleType, DeviceSensor[]> = {
  ROBOTAXI: [
    {
      id: 'LID-01',
      deviceId: 'DEV-ROBOTAXI-LIDAR-01',
      name: 'Roof High-Res 128ch LiDAR',
      type: 'LIDAR',
      deviceType: 'DEV_LIDAR',
      serialNumber: 'SN-LIDAR-88319',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Roof Center',
      firmware: 'v1.12.0',
      firmwareVersion: 'v1.12.0',
      fps: 30,
    },
    {
      id: 'LID-02',
      deviceId: 'DEV-ROBOTAXI-LIDAR-02',
      name: 'Front Solid-State Bumper LiDAR',
      type: 'LIDAR',
      deviceType: 'DEV_LIDAR',
      serialNumber: 'SN-LIDAR-88320',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Front Grille',
      firmware: 'v2.1.0',
      firmwareVersion: 'v2.1.0',
      fps: 30,
    },
    {
      id: 'RAD-01',
      deviceId: 'DEV-ROBOTAXI-RADAR-01',
      name: '77GHz Long-Range Front Radar',
      type: 'RADAR',
      deviceType: 'DEV_RADAR',
      serialNumber: 'SN-RADAR-44120',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Front Center',
      firmware: 'v2.0.1',
      firmwareVersion: 'v2.0.1',
    },
    {
      id: 'CAM-01',
      deviceId: 'DEV-ROBOTAXI-CAMERA-01',
      name: 'Front Stereo AI Camera Array',
      type: 'CAMERA',
      deviceType: 'DEV_CAMERA',
      serialNumber: 'SN-CAM-10928',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Windshield Top',
      firmware: 'v3.1.0',
      firmwareVersion: 'v3.1.0',
      fps: 60,
    },
    {
      id: 'V2X-01',
      deviceId: 'DEV-ROBOTAXI-V2X-01',
      name: 'CoreGuard C-V2X Security Gateway',
      type: 'V2X',
      deviceType: 'DEV_V2X',
      serialNumber: 'SN-V2X-99012',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Telematics Unit',
      firmware: 'v1.5.2',
      firmwareVersion: 'v1.5.2',
      latencyMs: 14,
    },
    {
      id: 'GNS-01',
      deviceId: 'DEV-ROBOTAXI-GNSS-01',
      name: 'Multi-Band RTK GNSS Receiver',
      type: 'GNSS',
      deviceType: 'DEV_GNSS',
      serialNumber: 'SN-GNSS-65123',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Roof Rear',
      firmware: 'v5.0.2',
      firmwareVersion: 'v5.0.2',
    },
    {
      id: 'CAN-01',
      deviceId: 'DEV-ROBOTAXI-CAN-01',
      name: 'Dual OBD-CAN Security Gateway',
      type: 'CAN_BUS',
      deviceType: 'DEV_CAN_GATEWAY',
      serialNumber: 'SN-CAN-30114',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Chassis Hub',
      firmware: 'v1.4.2',
      firmwareVersion: 'v1.4.2',
    },
  ],
  SHUTTLE: [
    {
      id: 'LID-01',
      deviceId: 'DEV-SHUTTLE-LIDAR-01',
      name: 'Front-Top 360° 128ch LiDAR',
      type: 'LIDAR',
      deviceType: 'DEV_LIDAR',
      serialNumber: 'SN-LIDAR-77119',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Roof Front',
      firmware: 'v1.12.0',
      firmwareVersion: 'v1.12.0',
      fps: 30,
    },
    {
      id: 'RAD-01',
      deviceId: 'DEV-SHUTTLE-RADAR-01',
      name: 'Front & Rear 77GHz Radars',
      type: 'RADAR',
      deviceType: 'DEV_RADAR',
      serialNumber: 'SN-RADAR-55201',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Front/Rear',
      firmware: 'v2.0.1',
      firmwareVersion: 'v2.0.1',
    },
    {
      id: 'CAM-01',
      deviceId: 'DEV-SHUTTLE-CAMERA-01',
      name: '8-Channel Surround Vision',
      type: 'CAMERA',
      deviceType: 'DEV_CAMERA',
      serialNumber: 'SN-CAM-20334',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Perimeter Ring',
      firmware: 'v3.1.0',
      firmwareVersion: 'v3.1.0',
      fps: 60,
    },
    {
      id: 'V2X-01',
      deviceId: 'DEV-SHUTTLE-V2X-01',
      name: 'Redundant C-V2X Ingress Transceiver',
      type: 'V2X',
      deviceType: 'DEV_V2X',
      serialNumber: 'SN-V2X-88110',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Main ECU',
      firmware: 'v1.5.2',
      firmwareVersion: 'v1.5.2',
      latencyMs: 12,
    },
    {
      id: 'GNS-01',
      deviceId: 'DEV-SHUTTLE-GNSS-01',
      name: 'Dual RTK GNSS Receiver',
      type: 'GNSS',
      deviceType: 'DEV_GNSS',
      serialNumber: 'SN-GNSS-65990',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Dual Antennas',
      firmware: 'v5.0.2',
      firmwareVersion: 'v5.0.2',
    },
    {
      id: 'CAN-01',
      deviceId: 'DEV-SHUTTLE-CAN-01',
      name: 'CAN FD Central Gateway',
      type: 'CAN_BUS',
      deviceType: 'DEV_CAN_GATEWAY',
      serialNumber: 'SN-CAN-40221',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Central Rack',
      firmware: 'v2.0.1',
      firmwareVersion: 'v2.0.1',
    },
  ],
  DELIVERY_POD: [
    {
      id: 'LID-01',
      deviceId: 'DEV-POD-LIDAR-01',
      name: 'Compact Solid-State LiDAR',
      type: 'LIDAR',
      deviceType: 'DEV_LIDAR',
      serialNumber: 'SN-LIDAR-66012',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Front Fascia',
      firmware: 'v1.12.0',
      firmwareVersion: 'v1.12.0',
      fps: 30,
    },
    {
      id: 'CAM-01',
      deviceId: 'DEV-POD-CAMERA-01',
      name: 'Dual Wide-Angle AI Cameras',
      type: 'CAMERA',
      deviceType: 'DEV_CAMERA',
      serialNumber: 'SN-CAM-30441',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Front/Side',
      firmware: 'v3.1.0',
      firmwareVersion: 'v3.1.0',
      fps: 60,
    },
    {
      id: 'RAD-01',
      deviceId: 'DEV-POD-RADAR-01',
      name: 'Ultrasonic & Radar Array',
      type: 'RADAR',
      deviceType: 'DEV_RADAR',
      serialNumber: 'SN-RADAR-33109',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Perimeter',
      firmware: 'v2.0.1',
      firmwareVersion: 'v2.0.1',
    },
    {
      id: 'V2X-01',
      deviceId: 'DEV-POD-V2X-01',
      name: 'V2X Micro Transceiver',
      type: 'V2X',
      deviceType: 'DEV_V2X',
      serialNumber: 'SN-V2X-77401',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Logic Board',
      firmware: 'v1.5.2',
      firmwareVersion: 'v1.5.2',
      latencyMs: 16,
    },
    {
      id: 'CAN-01',
      deviceId: 'DEV-POD-CAN-01',
      name: 'Micro CAN Gateway',
      type: 'CAN_BUS',
      deviceType: 'DEV_CAN_GATEWAY',
      serialNumber: 'SN-CAN-10022',
      status: 'ONLINE',
      deviceStatus: 'DEV_ONLINE',
      mountPosition: 'Motor Controller',
      firmware: 'v1.0.0',
      firmwareVersion: 'v1.0.0',
    },
  ]
};

export interface VehicleProfileDefaultConfig {
  model: string;
  speedLimit: number;
  assignedZone: string;
  firmwareVersion: string;
  latitude: number;
  longitude: number;
  status: string;
}

export const VEHICLE_PROFILE_DEFAULTS: Record<VehicleType, VehicleProfileDefaultConfig> = {
  ROBOTAXI: {
    model: 'Hyundai IONIQ 5 Robotaxi',
    speedLimit: 60.0,
    assignedZone: 'Gangnam District',
    firmwareVersion: 'v2.4.1',
    latitude: 37.4979,
    longitude: 127.0276,
    status: 'VEH_ACTIVE',
  },
  SHUTTLE: {
    model: 'Hyundai Solati Autonomous Shuttle',
    speedLimit: 40.0,
    assignedZone: 'Teheran-ro Autonomous Corridor',
    firmwareVersion: 'v3.1.0',
    latitude: 37.5045,
    longitude: 127.0490,
    status: 'VEH_ACTIVE',
  },
  DELIVERY_POD: {
    model: 'COEX RoboDelivery Pod X1',
    speedLimit: 25.0,
    assignedZone: 'COEX Smart Pedestrian Zone',
    firmwareVersion: 'v1.8.4',
    latitude: 37.5088,
    longitude: 127.0632,
    status: 'VEH_ACTIVE',
  },
};

// Realistic Waypoints in Gangnam, Seoul
export const GANGNAM_WAYPOINTS = [
  { lat: 37.5013, lng: 127.0396, name: 'Gangnam Station Cross' },
  { lat: 37.5045, lng: 127.0490, name: 'Yeoksam Station Junction' },
  { lat: 37.5088, lng: 127.0632, name: 'Samseong Station COEX' },
  { lat: 37.5140, lng: 127.0595, name: 'Bongeunsa Intersection' },
  { lat: 37.5172, lng: 127.0473, name: 'Cheongdam Station East' },
  { lat: 37.5195, lng: 127.0284, name: 'Sinsa Station Boulevard' },
  { lat: 37.5080, lng: 127.0255, name: 'Nonhyeon Station Avenue' },
  { lat: 37.4982, lng: 127.0278, name: 'Gangnam-daero South' },
];

export const GEOFENCE_BOUNDS = {
  minLat: 37.4900,
  maxLat: 37.5250,
  minLng: 127.0200,
  maxLng: 127.0700,
};

// Initial Demo Vehicles
export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'ROBOTAXI-105',
    vehicleId: 'ROBOTAXI-105',
    name: 'Gangnam RoboTaxi 105',
    type: 'ROBOTAXI' as VehicleType,
    vehicleType: 'ROBOTAXI' as VehicleType,
    vin: 'KN4CG2026TX10501',
    model: 'Hyundai IONIQ 5 Robotaxi',
    status: 'VEH_ACTIVE',
    speedLimit: 60.0,
    assignedZone: 'Gangnam District',
    firmwareVersion: 'v2.4.1',
    latitude: 37.4979,
    longitude: 127.0276,
    registeredAt: new Date(Date.now() - 3600000).toISOString(),
    lifecycleStatus: 'RUNNING' as const,
    lastHeartbeat: Date.now(),
    secondsSinceLastHeartbeat: 0,
    sensors: PRESET_SENSORS.ROBOTAXI,
    injections: {
      lidarFailure: false,
      v2xLatencySpike: false,
      gpsSpoofing: false,
      cameraOffline: false,
      canBusInjection: false,
    },
    lastTelemetry: null,
    routeProgress: 0.15,
    totalPacketsSent: 142,
  },
  {
    id: 'SHUTTLE-089',
    vehicleId: 'SHUTTLE-089',
    name: 'Teheran Shuttle S-89',
    type: 'SHUTTLE' as VehicleType,
    vehicleType: 'SHUTTLE' as VehicleType,
    vin: 'KN4CG2026SH08933',
    model: 'Hyundai Solati Autonomous Shuttle',
    status: 'VEH_ACTIVE',
    speedLimit: 40.0,
    assignedZone: 'Teheran-ro Autonomous Corridor',
    firmwareVersion: 'v3.1.0',
    latitude: 37.5045,
    longitude: 127.0490,
    registeredAt: new Date(Date.now() - 7200000).toISOString(),
    lifecycleStatus: 'RUNNING' as const,
    lastHeartbeat: Date.now(),
    secondsSinceLastHeartbeat: 0,
    sensors: PRESET_SENSORS.SHUTTLE,
    injections: {
      lidarFailure: false,
      v2xLatencySpike: false,
      gpsSpoofing: false,
      cameraOffline: false,
      canBusInjection: false,
    },
    lastTelemetry: null,
    routeProgress: 0.58,
    totalPacketsSent: 98,
  },
  {
    id: 'POD-104',
    vehicleId: 'POD-104',
    name: 'COEX Delivery Pod P-104',
    type: 'DELIVERY_POD' as VehicleType,
    vehicleType: 'DELIVERY_POD' as VehicleType,
    vin: 'KN4CG2026DP10471',
    model: 'COEX RoboDelivery Pod X1',
    status: 'VEH_ACTIVE',
    speedLimit: 25.0,
    assignedZone: 'COEX Smart Pedestrian Zone',
    firmwareVersion: 'v1.8.4',
    latitude: 37.5088,
    longitude: 127.0632,
    registeredAt: new Date(Date.now() - 10800000).toISOString(),
    lifecycleStatus: 'PAUSED' as const,
    lastHeartbeat: Date.now() - 4000,
    secondsSinceLastHeartbeat: 4,
    sensors: PRESET_SENSORS.DELIVERY_POD,
    injections: {
      lidarFailure: false,
      v2xLatencySpike: false,
      gpsSpoofing: false,
      cameraOffline: false,
      canBusInjection: false,
    },
    lastTelemetry: null,
    routeProgress: 0.82,
    totalPacketsSent: 34,
  }
];

